### ISSUE TITLE
PackageReferenceに対応しました（コンソールアプリで）

### ISSUE THREAD

**Issue by reniris** [jz5/package-licenses#3]
PackageReferenceに対応しました
PackageLicensesにメインロジックを移動しました
コンソールアプリPackageReferenceSampleを追加しました。
コマンドラインオプションでプロジェクトファイルを指定すると、ライセンスを取ってきます。

PackageLicenses.SampleとPackageLicenses.VisualStudioは変更していません。
PackageLicensesMod.VisualStudioは作りかけで動作しません。

https://github.com/reniris/package-licenses/tree/Mod
にソースがあります。動かない拡張機能のプロジェクトがあるのでプルリクエストにはしませんでした。

**Comment by jz5** [comment]
Marketplace の方で要望があったので、とりあえず PackageReference 対応入れてみました。
Issue になっていたのを失念していました。
Fork ありがとうございます。
Issue はクローズします。
